# Generated by Django 3.0.3 on 2020-02-19 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.BigIntegerField(editable=False, unique=True, verbose_name='card number')),
                ('balance', models.BigIntegerField(default=0, verbose_name='balance')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='creation date')),
            ],
            options={
                'verbose_name': 'card',
                'verbose_name_plural': 'cards',
            },
        ),
        migrations.CreateModel(
            name='CardHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия')),
                ('patronymic', models.CharField(max_length=100, verbose_name='patronymic')),
                ('phone_number', models.PositiveIntegerField(verbose_name='phone number')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='creation date')),
            ],
            options={
                'verbose_name': 'card holder',
                'verbose_name_plural': 'card holders',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ENROLLMENT', 'enrollment'), ('WRITE_OFF', 'write off')], max_length=12, verbose_name='transaction type')),
                ('amount', models.BigIntegerField(verbose_name='amount')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='creation date')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Card', verbose_name='card')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('CREATE', 'create'), ('DELETE', 'delete')], max_length=6, verbose_name='operation type')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='creation date')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Card', verbose_name='card')),
            ],
            options={
                'verbose_name': 'operation',
                'verbose_name_plural': 'operations',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='card_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.CardHolder', verbose_name='card holder name'),
        ),
    ]
